export const SUBIR_COPIA_POSTULACION = "SUBIR_COPIA_POSTULACION";
export const SUBIR_ARCHIVO_MATRICULA = "SUBIR_ARCHIVO_MATRICULA";
export const GUARDAR_USUARIO = "GUARDAR_USUARIO";
export const CERRAR_SESION = "CERRAR_SESION";

